# fly.toml app configuration file generated for dataingapp-lingering-sound-9491 on 2024-03-29T12:54:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dataingapp-lingering-sound-9491'
primary_region = 'ord'

[build]
  image = 'tedr/datingapp:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dsv721few"
  CloudinarySettings__ApiKey="596336822472499"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
